CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CPF_CNPJ VARCHAR(255) NOT NULL
);

CREATE TABLE BARBERS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL
);

CREATE TABLE ENTERPRISE(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(255) NOT NULL
);